plugins:
  - jekyll-sitemap
  - jekyll-feed

title: truongx.com
name: truongx.com
baseurl: ""
url: "https://truongx.com"
email: yo@truongx.com
x_username: 0xtruong
github_username:  truongx
instagram_username: truongx
linkedin_username: krzysztoftruong
calcom_username: truongx

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
      block:
          line_numbers: true

sass:
  sass_dir: css/partials
  style: compressed

permalink: /blog/:title/

repository: truongx/truongx.github.io